### ISSUE TITLE
ExportLicensePlate function throws exception on creating response

### ISSUE THREAD

**Issue by ricardocovo** [microsoft/MCW-Serverless-architecture#97] opened 2021-08-31 18:39 UTC
The code generates the file but fails when creating the response. 

Specifically this statement fails:

**req.CreateResponse(HttpStatusCode.OK, $"Exported {exportedCount} license plates");**

I haven't had the time to figure out exactly why it fails, but I found that removing the string makes it work. It might be related to versioning.

**Comment by codingbandit** [comment] 2021-09-12 00:06
I was unable to reproduce this issue, however, I updated the YML document to deploy version '3.1.x', so that may be the issue here. Please re-test with the DOTNET_VERSION value of '3.1.x'. Thanks.

**Comment by DawnmarieDesJardins** [comment] 2021-09-17 20:37
No additional comments so closing this issue.  Please reopen if you're still having trouble. Thank you!

**Closed by DawnmarieDesJardins** 2021-09-17 20:37 UTC
