### ISSUE TITLE
Couldn't publish to function app from VS code (mac)

### ISSUE THREAD

**Issue by mimuta** [microsoft/MCW-Serverless-architecture#56] opened 2019-11-22 15:46 UTC
On VS Code (Mac) publish didn't work.

1. dotnet restore and dotnet build worked, as well as build from VS Code
2. But deploy didn't work:

![image](https://user-images.githubusercontent.com/16953363/69439566-85643f00-0d47-11ea-8893-9a2a578c4933.png)

3. I also tried from Visual Studio on Mac (not code) but have the same error.

I tried to publish 3 other apps and working ok.

Possible something with path.

**Comment by DawnmarieDesJardins** [comment] 2019-12-03 21:07
@joelhulen 
Hey Joel, any update on this one?
Thanks! Dawnmarie

**Comment by joelhulen** [comment] 2019-12-04 05:33
@DawnmarieDesJardins 
I cannot reproduce this problem on a Windows machine. I am working on getting my hands on a Mac to reproduce the issue. The error message shown in the screenshot isn't very helpful, unfortunately.

**Comment by DawnmarieDesJardins** [comment] 2019-12-04 23:13
@mimuta - 
Hello.  Are you still unable to complete the lab?  Can you please provide us with some additional information?  The screenshot you provided does not give our author enough information to troubleshoot.  Thank you.

**Comment by joelhulen** [comment] 2019-12-09 18:49
@mimuta - Can you please update us with a status on this? Are you still having this issue?

**Comment by DawnmarieDesJardins** [comment] 2019-12-16 18:43
Closing issue as no further response from field.  Will reopen if needed.

**Closed by DawnmarieDesJardins** 2019-12-16 18:43 UTC
