### ISSUE TITLE
Exercise 2: Task 1: Step 4: Templates not available in TollBoothEvent Function App

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Serverless-architecture#90] opened 2021-05-07 12:17 UTC
Hi @DawnmarieDesJardins,

Can you please help here? 12th May is the Prod Lab delivery.

Getting issues while performing the following section of the Lab:

[Exercise 2: Task 1:](https://github.com/microsoft/MCW-Serverless-architecture/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Serverless%20architecture.md#task-1-create-a-function-to-save-license-plate-data-to-azure-cosmos-db) Step 4: As per the guide - User needs to enter event grid into the Select a template filter box, select the Azure Event Grid trigger template, and then enter SavePlateData into the New Function name field.

- For me, while adding funtion to TollBoothEvent function app, there are only two Templates available as shown below:

  ![image](https://user-images.githubusercontent.com/50323628/117447435-273b1400-af5b-11eb-90a0-ad0a33f619ed.png)

- When tried on searching for Grid, it shows as below:

  ![image](https://user-images.githubusercontent.com/50323628/117447564-4d60b400-af5b-11eb-9ca0-075e8ab5c2bd.png)

Thanks,
Seerat Arora

**Comment by SeeratArora** [comment] 2021-05-10 06:40
Hi @DawnmarieDesJardins, can we please have an update on this?

**Comment by daronyondem** [comment] 2021-05-10 15:08
Hi @SeeratArora,

I'm not able to reproduce. This is what I see when I create a new function app set to run NodeJS code.

![image](https://user-images.githubusercontent.com/2984187/117681101-6f0ba680-b1ba-11eb-87d0-4c743459e066.png)

- Where does the `Learn more` link lead to? Can you share it?
- Additionally, can you try to create a brand new function app set to run NodeJS and try creating a new function to see if it changes anything?
- Finally, if you have the chance can you try the same in a separate subscription and let us know what you see. 

The last two steps can help us isolate the root cause of the issue. 

Thanks

**Comment by SeeratArora** [comment] 2021-05-11 08:21
Hi @daronyondem,

We will try the cases you stated, and will get back to you.

Thanks!

**Comment by riwasa** [comment] 2021-05-13 12:15
I ran this lab yesterday, and had two students also run into this issue. After deploying from Visual Studio, when they viewed either the TollBoothFunctions or the TollBoothEvents function apps, in both cases they saw the ProcessImage and ExportLicensePlates functions, and when they tried to create a new function in TollBoothEvents they did not see Event Grid as a trigger option. 

I thought they might have accidentally deployed the C# apps to the Node.js function by mistake, but when I tried that I did not see the same type of errors they were getting in the portal, and the students said they did not deploy to the wrong function initially, so I haven't been able to reproduce this either, but did observe the issue in the students' resource groups. 

I'm not sure if the fact both function apps are using the same storage account and/or that the storage account has the hierarchical name space turned on impacts anything (this shouldn't be the issue since it does seem to work in my own subscription, but not sure if either might be a factor regardless).

**Comment by timahenning** [comment] 2021-05-13 12:26
Hi @riwasa,

Sounds like this might be a difficult issue to reproduce.  In the short term, we are going to close this issue.  If you are able to successfully reproduce the problem, we can re-open the issue with the additional information to resolve the problem.

Tim

**Comment by riwasa** [comment] 2021-05-13 12:58
For reference in case anyone comes across the issue and is searching for a solution, simply delete the TollBoothEvents function app (NOT the TollBoothFunctions function app), then create a new Node.js function app with the same name (TollBoothEvents-<prefix>) and then follow the lab instructions as written. Since TollBoothEvents doesn't contain any other special configuration settings set up by the ARM template, this seems to work fine to get around the issue.

**Comment by SeeratArora** [comment] 2021-05-17 05:51
Hi @riwasa,

We had the same issue again i.e., while adding funtion to TollBoothEvent function app, Event grid trigger template is not available under templates.

We can provide you a fresh environment so that you can test it from the start and review it or else we can reproduce the issue and provide you that environment.

Please let us know which of these will work for you.

Thanks

**Comment by sumitmalik51** [comment] 2021-05-24 10:24
Hello Tim, the issue is resolved as reported on Mail, we are closing the issue thanks.

**Closed** 2021-05-24 10:25 UTC
